stages:
  - test

variables:
  INNER_NAME: "RHCSKY"

test_flutter:
  tags:
    - runner
  stage: test
  script:
    - echo INNER_NAME=$INNER_NAME
  only:
    - main
    - dev
    - merge_requests

test_nodejs:
  tags:
    - runner
  stage: test
  script:
    - echo INNER_NAME=$INNER_NAME
  only:
    - main
    - dev
    - merge_requests

test_flask:
  image:
    name: pytorch/pytorch:latest
  tags:
    - runner
  stage: test
  before_script:
    - cd flask-api
    - export PATH=/opt/conda/bin:$PATH
    # - python3 -m pip install -r requirements.txt
  script:
    - echo INNER_NAME=$INNER_NAME
  only:
    - main
    - dev
    - merge_requests