stages:
  - test

variables:
  INNER_NAME: "RHCSKY"

test_flutter:
  tags:
    - runner
  stage: test
  script:
    - echo INNER_NAME=$INNER_NAME
  only:
    - main
    - dev
    - merge_requests

test_nodejs:
  tags:
    - runner
  stage: test
  script:
    - echo INNER_NAME=$INNER_NAME
  only:
    - main
    - dev
    - merge_requests

test_flask:
  image:
    name: ubuntu:18.04
  tags:
    - runner
  stage: test
  before_script:
    - cd flask-api
    - export PATH=$PATH:/opt/conda/bin
  script:
    - python -m pip install -r requirements.txt
    - echo INNER_NAME=$INNER_NAME
  only:
    - main
    - dev
    - merge_requests